### ISSUE TITLE
[NEED DETAILS] Ubuntu 22.04 LTS not reachable

### ISSUE THREAD

**Issue by Sub-7** [Balzabu/disable-cloud-init#1]
Ubuntu 22.04 LTS not reachable

**Comment by Balzabu** [comment]
Hey, mind sharing more details about the issue? If my script leaves your server unreachable, reaching out to your Hosting Provider is a good move.

Typically, such operations shouldn't compromise your server's connectivity in any way.

**Comment by Balzabu** [comment]
Hello, I'm closing this issue due to lack of details.
